### PR TITLE
custom: add Zul'jin banner

### PR DESCRIPTION
**Pull request by yuna9**
Hold for official Zul'jin release later today.

### CODE REVIEW

**Comment by kalebhermes** [comment]
Code looks good. Only issue is that we need the left, right and top sides of the banner to gradient to black. This allows for support for people with super high resolution displays. The image will fade into the black background, rather than cut off sharply.

**Comment by yuna9** [comment]
As discussed, Kaleb is making another version of the banner image.

**Review by kalebhermes — APPROVED** [review]
👍 📦 🚢 🚀

**Review by kalebhermes — APPROVED** [review]
📦 🚢 🚀

**Comment by yuna9** [comment]
[Patch notes](http://us.battle.net/heroes/en/blog/20407400/heroes-of-the-storm-patch-notes-january-4-2017-1-4-2017) rolled out.

**Pull request merged**
